# @package _global_
exp_name: training_kto_qwen2.5_base


# Model arguments
model_name_or_path: ???
model_revision: main
torch_dtype: bfloat16
trust_remote_code: True
attn_implementation: flash_attention_2

# Data training arguments
chat_template: ???
dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 1.0
dataset_splits:
  - train
  - test
preprocessing_num_workers: 15
dataset_num_proc: 15
truncation_side: left
auto_insert_empty_system_msg: false  # false for qwen

# DhPOTrainer arguments
output_dir: ???
run_name: ???
beta: 0.5
per_device_train_batch_size: ???
per_device_eval_batch_size: ???
gradient_accumulation_steps: ???
eval_strategy: ???
eval_steps: ???
report_to:
  - ???
auto_find_batch_size: true
bf16: true
do_eval: true
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 5.0e-7
log_level: info
logging_steps: 1
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1800
num_train_epochs: 1
optim: paged_adamw_32bit  # adamw_torch_fused
overwrite_output_dir: true
save_strategy: ???
save_steps: ???
save_total_limit: ???
seed: 42
warmup_ratio: 0.1