# @package _global_
defaults:
  - /training_configs/base_dpo_config

exp_name: training_dpo_qwen2.5_base

training_configs:
# Model arguments
  model_name_or_path: qwen-25-1.5b-base-sft

# Data training arguments
  chat_template: "src/data/chat_templates.json"

# SFT trainer config
  output_dir: qwen-25-1.5b-base-dpo
  run_name: qwen-25-1.5b-base-dpo
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 6
  gradient_accumulation_steps: 4
  eval_strategy: steps
  eval_steps: 10
  report_to:
    - wandb
  save_strategy: "steps"
  save_steps: 100
  save_total_limit: 10

